### ISSUE TITLE
How to get the session ID?

### ISSUE THREAD

**Issue by remcotolsma** [ericmann/wp-session-manager#24]
Is there a specific reason why the session ID is not accessible? I now use the following code to retrieve the session ID:

``` php
$session_id = substr( filter_input( INPUT_COOKIE, WP_SESSION_COOKIE, FILTER_SANITIZE_STRING ), 0, 32 );
```

It would be nice if the session ID is al available trough an public function.

``` php
$wp_session = WP_Session::get_instance();
$session_id = $wp_session->get_session_id();
```

If there is an specific reason why it's not accessible then that's ok to. Maybe it's nice to mention this in the comments of the session ID property:

https://github.com/ericmann/wp-session-manager/blob/1.1.2/class-wp-session.php#L20-L25

**Comment by NewriseJM** [comment]
Is there now (over 5 years later) a way that the session_id is accessible? Can't find anything about it anywhere...

Great plugin by the way, thanks! Been using it for a while now and I can't miss it anymore.

**Comment by ericmann** [comment]
As the plugin now uses PHP's native session interface, you can use the native [`session_id()`](https://www.php.net/manual/en/function.session-id.php) function to retrieve it.
