### ISSUE TITLE
Session will live for only 24 minutes no matter what

### ISSUE THREAD

**Issue by Tklaversma** [ericmann/wp-session-manager#25]
Hi Eric,

First of all, amazing plugin!

My problem.
It seems to me that no matter what, the sessions will only live for 24 minutes. If I read a session variable after it has been set 10 minutes ago, the expiration should reset to 24 minutes, right?

<i>"By default, session variables will live for 24 minutes from the last time they were accessed - <b>either read or write</b>."</i>

I use the following code to set an variable on page load

```
$wp_sessions = WP_Session::get_instance();
$wp_sessions['id'] = $id;
```

and use the following to read. If session doesn't exist, I redirect to the login page.

```
$wp_sessions = WP_Session::get_instance();
if ( isset( $wp_sessions['id'] ) ) {
    return true;
}
wp_redirect( 'http://www.example.com/login/', 302 );
exit;
```

Hope you can help me out.

Regards,
TK

**Comment by natebeaty** [comment]
FWIW I have the same problem, no matter where I put:

```
// Set wp_session_expiration to 24 hours and wp_session_expiration_variant to 10 minutes
add_filter('wp_session_expiration', function() { return 24 * 60 * 60; });
add_filter('wp_session_expiration_variant', function() { return 10 * 60; });
```

It has no effect on the expiration or expiration_variant.

**Comment by joelambert** [comment]
It's because the session is created in the `plugin_loaded` action which happens before any theme code can run. So adding the filters has no effect as the thing that runs the filters has already executed before your code can add them to the queue.

I worked around this by creating a small custom plugin that can apply the custom filters before the WP Session plugin initialises for the first time.

Add something like the following to a custom plugin file:

```php
add_action('plugins_loaded', function () {
    add_filter('wp_session_expiration_variant', function ($value) {
        return 20 * 60 * 60;
    });

    add_filter('wp_session_expiration', function () {
        return 24 * 60 * 60;
    });
}, 1);
```

**Comment by Tklaversma** [comment]
It has been a while, but @joelambert his solution works. It would be nice if the plugin FAQ would also be updated on the WordPress plugin page (wordpress dot org/plugins/wp-session-manager/).

**Comment by VivekManglani** [comment]
@ericmann how do we handle this in 3.0?

**Comment by Tklaversma** [comment]
First of all make a wrapper class, so that its easier to maintain your sessions:

```
<?php

namespace App\Sessions;

/**
 * Wrapper class for WP_Session that holds functionality to get, set and delete current sessions and sessiondata
 * and that adds the use of serialize() and unserialize().
 */
class SessionController
{
    /**
     * Get all sessions.
     *
     * @return array
     */
    public function get_sessions()
    {
        return $_SESSION;
    }

    /**
     * Get session by given key.
     *
     * @param string $key - Unique identifier of the session.
     *
     * @return bool|mixed
     */
    public function get($key)
    {
        return isset($_SESSION[$key]) ? unserialize($_SESSION[$key]) : false;
    }

    /**
     * Store data in a session with given key and value.
     *
     * @param string $key   - Unique identifier for the session.
     * @param mixed  $value - The value for the session.
     *
     * @return void
     */
    public function set($key, $value)
    {
        unset($_SESSION[$key]);
        $_SESSION[$key] = serialize($value);
    }

    /**
     * Delete session by given key.
     *
     * @param string $key - Unique identifier of the session.
     *
     * @return void
     */
    public function delete($key)
    {
        if ($_SESSION[$key]) {
            unset($_SESSION[$key]);
        }
    }

    /**
     * Remove all existing sessions.
     *
     * @param bool $deleteSpecials - Indicates whether or not to delete specials sessions as well.
     *
     * @return void
     */
    public function delete_all($deleteSpecials = false)
    {
        $specialKeys = [
            'LAST_ACTIVITY',
        ];

        if (count($_SESSION) > 0) {
            foreach ($_SESSION as $k => $v) {
                if ($deleteSpecials !== true) {
                    if (in_array($k, $specialKeys, true)) {
                        continue;
                    }
                }

                unset($_SESSION[$k]);
            }
        }

        if ($deleteSpecials === true) {
            $_SESSION = [];
        }
    }
}
```

Since 3.0 makes use of the default global session variable, we have to keep track of the expiration ourselfs.
What most people do, is set a session that keeps track of the last activity, which essentially does the same as wp_session_expire().

```
<?php

/**
 * Session expiration.
 *
 * Set the expiration time of our (WordPress) sessions to 1 hour.
 */
if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY'] > (60 * 60 * 1))) {
    session_unset();
    session_destroy();
}
$_SESSION['LAST_ACTIVITY'] = time();
```

I hope this is what you are looking for.

**Comment by ericmann** [comment]
Since we're using native session functionality, you can either:

- Use PHP's [native session lifetime configuration](https://stackoverflow.com/a/1270960/326224) to tweak how long a session will live
- Set a "last activity" time in the session and manually clear things up. Though I _wouldn't_ recommend the use of a full wrapper class as outlined by @Tklaversma above. Instead:

```
function purge_stale_sessions() {
    if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY'] > (60 * 60 * 1))) {
        session_unset();
        session_destroy(); // Purge stored session data
        session_start(); // Restart the session
    }
    $_SESSION['LAST_ACTIVITY'] = time();
}
add_action('wp_session_init', 'purge_stale_sessions');

**Comment by Tklaversma** [comment]
@ericmann The foremost reason to use a wrapper class is that you can (and did 👎 ) change how the library works. When I updated to version 3.0 in the beginning, all I had to do is change **my functions**, which only took 2 min. Others have had problems since they used your code through there whole project and had to change it everywhere. No bad feelings, but not recommending without a valid reason makes no sense.

Besides the above, I do like your solution to hook on the ``wp_session_init()``

**Comment by ericmann** [comment]
@Tklaversma Version 3.0 was not intended to be backwards compatible. This is why the major version incremented from 2.X to 3.X. That being said, community members have contributed a patch to the latest version (3.0.3) that brings back the global `WP_Session` object and allows you to _still_ use the exact same code as you did with the older versions.

[With this change](https://github.com/ericmann/wp-session-manager/blob/master/includes/deprecated.php#L163), `WP_Session` _is itself_ a wrapper class over the regular `$_SESSION` functionality. All of the other `wp_session_{etc}` functions remain and do the exact same thing they did before (which was mimic the standard Session functionality), they just now fall through to native Session functions and flag themselves as deprecated.
