### ISSUE TITLE
Github versions vs Wordpress plugin page version

### ISSUE THREAD

**Issue by danimalweb** [ericmann/wp-session-manager#28]
I've noticed the version in the GH repo is 1.2.0 and the WP Plugin page shows 1.1.2.

I presume the WP Plugin page version is not up to date? Any plans to update this?

Also, is version 1.2.0 compatible with WP 4.1?

Thanks.

**Comment by mishtershmart** [comment]
I'm also curious about this. Has this project been abandoned, or is the plugin still being looked after?

**Comment by ericmann** [comment]
The plugin is currently in the midst of a major refactor that makes this issue moot ... stay tuned for v2.0.
