### ISSUE TITLE
Documentation enhancement to reduce wp_session_expiration grief

### ISSUE THREAD

**Issue by SungamR** [ericmann/wp-session-manager#30]
The code works great but it seem to be confusion around the web about how to use it. It tripped me also before I actually read the comments in class-wp-session.php. I think it could be addressed by mentioning the wp_session_expiration_variant in the readme.md. 

When debugging sessions its commonplace to make them short lived. _The effect of just lowering the wp_session_expiration to lets say 3 minutes, is that you will get a new session every third minute regardless of how many times you hit the site._ This is a bit confusing until you realize that the wp_session_expiration_variant also need to be lowered. It must in fact always be the lowest value of the two and I think this isn't clear enough.

``` php
/* This code will create a session that lives for 120 seconds and the 
time will be updated when less than 60 seconds remain. */
add_filter( 'wp_session_expiration', function() { return 120; } );
add_filter( 'wp_session_expiration_variant', function() { return 60; } );
```

**Comment by ericmann** [comment]
The plugin is currently in the midst of a major refactor that makes this issue moot ... stay tuned for v2.0.
