### ISSUE TITLE
PHP Warning: delete_old_sessions()

### ISSUE THREAD

**Issue by thefrosty** [ericmann/wp-session-manager#32]
Getting a PHP Warning:
Invalid argument supplied for foreach() in /includes/class-wp-session-utils.php on line 86

Triggered by:
WP_Session_Utils::delete_old_sessions() /includes/wp-session.php:131

**Comment by thefrosty** [comment]
For some reason, prepare() is returning the results as NULL, and when removed the query works as expected. No Idea why yet.

**Comment by ericmann** [comment]
I'm not sure where you're using `prepare()` ... the query just uses `->get_results()` as the only variable component of the query is explicitly sanitized just before it's used.

So no, haven't seen this before. Could add an `is_array()` check on `$keys` before iterating it, though.

**Comment by thefrosty** [comment]
Oops, sorry. I am using a forked version when prepare is being used. My bad.
