### ISSUE TITLE
Using it without a wp plugin

### ISSUE THREAD

**Issue by kodeine** [ericmann/wp-session-manager#33]
as the title says, is it possible to use it as an object package and not as a wp plugin?
Or it must be used as a plugin, i was thinking to fork and redo the implementation so it can support psr4 and supports usage without needing to install it as a plugin in wp.

**Comment by danimalweb** [comment]
I looked in to using at as an object package and it looked like I'd need to do something similar to the way Wordpress Easy Digital Downloads are using this code. Looking through their code they used a custom class as a wrapper, however the original plugin looked heavily modified.

It would be awesome to get this as a standalone composer package. Let me know if you start a fork and I'd consider contributing some time to help out.

**Comment by ericmann** [comment]
> Let me know if you start a fork and I'd consider contributing some time to help out.

I'd be more than happy to roll any necessary changes in here ... so maybe submit a PR when you're ready?

**Comment by arbet** [comment]
I'm personally using it as a library in my WP plugin. I just include the main plugin file in my code, and then it just works.

https://github.com/arbet/wordpress-linkedin-login/tree/master/includes/lib/wp-session-manager-1.2.0
