### ISSUE TITLE
SQL injection attempts in wp_session option names

### ISSUE THREAD

**Issue by natebeaty** [ericmann/wp-session-manager#39]
I just spent a dumb amount of time debugging why sessions weren't being garbage collected (there were 785,000+ entries in the wp_options table matching `_wpsession%`), and eventually found out there were SQL injection attempts causing a SQL error in the cronjob DELETE call. Here are some of the nefarious names in question:

```
'_wp_session_fe6264b27973c947e939295a9b280c67',
'_wp_session_expires_aa2f368b8b6c02591eec53f93c3aeb3f',
'_wp_session_aa2f368b8b6c02591eec53f93c3aeb3f',
'_wp_session_expires_-1 AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_S',
'_wp_session_-1 AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_S',
'_wp_session_expires_-1' AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_',
'_wp_session_-1\' AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_',
'_wp_session_expires_-1" AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_',
'_wp_session_-1\" AND (/*!SElEcT*/ 8041 FRoM(/*!selEcT*/ COUNT(*),CONCAt((/*!SelEcT*/ concat(0x7c3a3a3a3a,substring(database(),1,52),0x3a3a3a3a7c) ),floor(rand(0)*2))x FRoM INFORMATION_',
'_wp_session_expires_e7d721fbe224e5869829bf684b164c99',
'_wp_session_e7d721fbe224e5869829bf684b164c99',
'_wp_session_expires_5b93f49f190aa8c361af00f4407cb214',
'_wp_session_5b93f49f190aa8c361af00f4407cb214'
```

I'm using the plugin in a Bedrock/Sage setup (https://github.com/firebelly/scb). I'm not sure how these were able to be injected (any ideas?), but the cronjob could be adjusted to use `$wpdb->escape()` instead of `addslashes()` to at least not bomb if this came up.

**Comment by ericmann** [comment]
The plugin is currently in the midst of a major refactor that makes this issue moot ... stay tuned for v2.0.

**Comment by natebeaty** [comment]
Well it's happening again, with 177953 entries matching `_wpsession%` because the cronjob won't run to clean them out due to H@xx0r garbage like above. 

I'll switch to just using native PHP sessions. Not sure why I was using this plugin in the first place, honestly.

**Comment by ericmann** [comment]
If native sessions are sufficient for your use case, feel free. The advantage of this plugin over native sessions only applies in load balanced environments where users might be hitting a different PHP server each time. If that's not your situation, native sessions will be faster than the PHP/DB overhead introduced by the plugin.

This all being said, the [Sessionz](https://github.com/ericmann/sessionz)-based rewrite is still pending and will remove this concern (there won't be any garbage collector exposed in such a way). If you're building something separate, Sessionz itself might be a good place to start. It leverages native sessions under the hood (as described in the readme's Quick Start) but also pulls the data in-memory for faster reads while the request is in process.

**Comment by natebeaty** [comment]
That makes sense. The only thing I'm using it for is to get a session_id to allow users to create post collections (pretty much a shopping cart), and it's on a single server, with pretty low traffic. PHP sessions should be sufficient for my low-tech need. Good luck with the rewrite!
