### ISSUE TITLE
Where / when should I add the filter: wp_session_expiration

### ISSUE THREAD

**Issue by reekrd** [ericmann/wp-session-manager#45]
Hi. 

I'm having troubles figuring out how to get the filter to work. I've tried placing it directly in functions.php and also in a after_setup_theme action but to no avail.

If you could be so kind to give me a hint on where to run the filter.

add_filter( 'wp_session_expiration', function() { return 60 * 60; } ); // Set expiration to 1 hour

Much appreciated
.rickard

**Comment by joelambert** [comment]
This is how we work around this: https://github.com/ericmann/wp-session-manager/issues/25#issuecomment-299819341
