### ISSUE TITLE
Getting the session manager to work on WPEngine

### ISSUE THREAD

**Issue by nishan-mills** [ericmann/wp-session-manager#50]
Hey @ericmann, thanks for the great plugin, we are hosting our site on WPE currently which has some aggressive caching in place. We have had _wp_session excluded on that cache, however seeing a behaviour where in incognito mode the cookie does not get set, thereby none of the session functions working. I believe WPE uses memcached for their object storage. Can you shed any light on this?

**Comment by ericmann** [comment]
That's something you'll have to work on directly with WP Engine. In addition to using Memcached for object storage, they use Varnish for front-end caching. If the cookie isn't set to begin with, then you'll be hitting the (Varnish) cache in incognito mode and won't even trigger the session engine in the first place.

This being said: sessions for anonymous users typically means you need to forgo the use of _all_ front-end caching in the first place. That might not be your intention, and it will definitely hurt your site's performance. If you just need sessions on a specific page, maybe work with WP Engine to keep that single page from living in Varnish (which means requests to that page will trigger the session manager, set the cookie, and allow users to bypass the cache elsewhere as well).

I'm closing this for now as, really, this is a host-level issue and not something I can manage at the code level. If WPE comes back with information that changes that assumption, feel free to reopen.
