### ISSUE TITLE
Move sessions to a custom table

### ISSUE THREAD

**Issue by glagonikas** [ericmann/wp-session-manager#51]
We've been this plugin as it came bundled with another one. We've got a relatively busy site and that results in loads of sessions being generated.

In a year's time and whilst the business is still growing our options table has reached an auto increment value of 29m (obviously not all of them come from this plugin). We gave adjusted the garbage collection to clear all expired sessions, however we still have a lot of unecessary data and read/writes on our options table. This slows down all pages as most plugins and core use the options table on every page load.

Having read #36 seems obvious you understand the necessity of moving away from the options table on onto a custom one. If that table is well written, it would make it a breeze to manage sessions, just like WooCommerce has done with their sesssion management table and would not affect any other parts of the site.

Considering it's now over a year and a half after you commented on #36 and over half a year since #42 (which still doesn't appear to use a new table), i wonder if this plugin is still actively maintained, or not.

I appreciate you're probably busy with other stuff and creating v2 is probably a low priority at this stage, but looking at your code, a refactor of the session storage doesn't appear to be a major change.

I wouldn't mind sending a pull request, assuming you'd merge it, so we can get this implemented soon (weeks, rather than months).

**Comment by ericmann** [comment]
> I wonder if this plugin is still actively maintained, or not.

It is. But I make literally $0 on this project, meaning it's somewhat of a low priority for me. More than willing to pick of development and ship features if someone is willing to pay for that time.

> I wouldn't mind sending a pull request, assuming you'd merge it, so we can get this implemented soon (weeks, rather than months).

I wouldn't mind reviewing a pull request, and definitely merge things on a shorter timeframe than months ;-)

That being said; closing this for now. Please open a new issue when you submit your PR for further discussion.
