### ISSUE TITLE
Can I include wp session manager in comemrcial plugin?

### ISSUE THREAD

**Issue by rkbwp** [ericmann/wp-session-manager#53]
Hi there,

   First of all thank you for a wonderful plugin. I want to know that can I include your WP Session manager in my plugin that I am planning to sell on different marketplaces?

Thank you

**Comment by ericmann** [comment]
The plugin is distributed under the terms of the [GNU GPL, version 2](https://opensource.org/licenses/GPL-2.0) (or, at your discretion, any later version). The requirements of that license are that any derivative or bundled works _must also_ be distributed under the terms of the same license.

If your commercial product will also be shipping with the GNU GPL, then have at it! :-)

If for any reason you wish to use a different license, either one that's more restrictive _or_ one that's more permissive (i.e. the [MIT license](https://opensource.org/licenses/MIT), which does not require derivatives to be distributed under the same) we'll have to have a deeper conversation about that offline. I'm not opposed to permitting it, but I'd want to:

1. Understand where and how you'll be distributing your derivative work
1. Understand how _you_ will be profiting from this directly
1. Discuss a potential licensing fee for allowing you to distribute the code under a different license

Feel free to [email me](mailto:eric@eamann.com) if you want to discuss things further.
