### ISSUE TITLE
Version 2.0 Does Not Appear To Work

### ISSUE THREAD

**Issue by bsmcgillis** [ericmann/wp-session-manager#54]
I updated this plugin to version 2.0 and values are no longer being stored correctly.

Here is my test code ( I've tried this on two different sites ):

```
function test_session_plugin(){
	$wp_session = WP_Session::get_instance();
	$wp_session['testing'] = 'test';

	echo '<pre>'; print_r( $wp_session ); echo '</pre>'; //@DEBUG
}
add_action( 'init', 'test_session_plugin' );
```

This is what the output of the $wp_session variable is: 
```
WP_Session Object
(
    [session_id] => d9748edf3d29e6cd5814e973ed83d512
    [expires:protected] => 1512403822
    [exp_variant:protected] => 1512403462
    [container:protected] => t
    [dirty:protected] => 1
)
```
When I comment out the line that sets the session variable, I get the same output. It appears to be storing the data. It just stores it incorrectly. 
The previous version of the plugin worked without issue.

**Comment by ericmann** [comment]
Will get this fixed ASAP. Thanks for the report.

**Comment by ericmann** [comment]
Fixed in https://github.com/ericmann/wp-session-manager/commit/1d517cd28a1eb1f75ff97ad115561a180e6fe602
