### ISSUE TITLE
3.0 breaks any plugin expecting a WP_Session object

### ISSUE THREAD

**Issue by griffbrad** [ericmann/wp-session-manager#61]
In 3.0, you're now just returning the $_SESSION super-global from the WP_Session::get_instance() method.  This breaks any plugin that was checking that an object was a WP_Session (either with instanceof or a type hint).

To preserve backward compatibility, it should be possible to instead continue returning a WP_Session object from get_instance().  The array access methods in WP_Session would be different than the 2.0 versions in that they'd only be reading from and writing to $_SESSION internally, but you'd avoid breaking any plugins expecting a WP_Session object.

Does that make sense?  Would it be helpful if I wrote this up and submitted a patch?

Thanks for your work on 3.0.  I can tell a lot of effort went into it.

**Comment by griffbrad** [comment]
I went ahead and submitted this pull request to address the issue:
https://github.com/ericmann/wp-session-manager/pull/62

Let me know what you think.

Thanks!

**Comment by thedotmack** [comment]
+1 on this. I just updated then freaked out and reverted once I realized this whole thing was changed

**Comment by ericmann** [comment]
Fixed with #62
