### ISSUE TITLE
$wp_session vs $_SESSION vs WP_Engine

### ISSUE THREAD

**Issue by willenglishiv** [ericmann/wp-session-manager#64]
Hey Eric,

I realize you guys moved the plugin up to v3 and started using the native $_SESSION.

However, $_SESSION is disabled on WP-Engine platforms, and I was using a previous version of your plugin as a makeshift $_SESSION var.  

Was there a philosophical reason to move to $_SESSION? Is there a fork with the functionality being still aligned with $wp_session or something similar?  Thanks in advance.

**Comment by ericmann** [comment]
There isn't a non-native fork of the plugin that will move forward with feature development. That being said, I'd highly recommend remaining on the 2.X branch of the plugin until we can sort out the incompatibility with WP Engine's platform. 2.0.2 uses the same custom DB table, but _still_ uses the older style of the custom session interface (3.X was where we implemented native `$_SESSION` support).

I'll leave this open for now while I reach out to WP Engine directly for a more concrete resolution.

In the mean time, you can download v2.0.2 from:
- https://github.com/ericmann/wp-session-manager/releases
- https://wordpress.org/plugins/wp-session-manager/advanced/ (Scroll to the bottom of the page)

**Comment by jschrab-lc** [comment]
Just checking in - has WP Engine staff been helpful at all here? Any progress?

**Comment by ericmann** [comment]
I'll reach out again today ...

**Comment by miklb** [comment]
ping as I'm running into this today.

**Comment by ericmann** [comment]
To update everyone: the official word from WP Engine is that session support will be disabled by default on their platform. There doesn't seem to be any room for negotiation, at least according to what I got from their support team. The entire goal of this plugin was to provide database-backed session support for WordPress, and the latest version uses the _native_ session functionality of PHP to do that as it's less error prone than trying to roll our own implementation. Regardless, WP Engine doesn't seem interested in supporting that functionality on their platform.

In short: **WP Engine refused to provide a workaround when I asked for assistance.**

That being said, I'd strongly encourage you to reach out directly to see if you can get movement for your own projects. Their team has been supportive of one-off changes to support specific projects in the past. They just wouldn't open up a _global_ way to leverage an alternative session handler.

If they still won't work with you, you have a couple of options:
1. Switch hosts. Yes, I know this sucks, but might be the best option. I personally recommend [Liquid Web](https://www.liquidweb.com/products/managed-wordpress/), who provides a similar level of managed WordPress hosting. Alternatively, give [Pantheon](https://pantheon.io/product/wordpress-hosting) a try. They've got a similar "native sessions" plugin based on this work, so I can definitely say WP Session Manager will work on their platform.
1. Just stick with v2.0.2 - This isn't my recommended path of action as you won't get any further updates ... but it might be workable for you.
