### ISSUE TITLE
Database sessions not automatically clearing

### ISSUE THREAD

**Issue by ericmann** [ericmann/wp-session-manager#77]
From: https://wordpress.org/support/topic/understanding-confirmation-sessions-expiration-and-session-gc_probability/

I would like confirmation that I am understanding the following correctly.

While using WP Session Manager, I am seeing MANY stale sessions that do not delete themselves from the database. I am in an Ubuntu hosted environment where session.gc_probability is set to zero. This appears to be a default thing for Ubuntu/Debian. For those environments, expired session cleanup is done by way of a cron task – BUT those environments assume file-based sessions, not database sessions (such as WP Session Manager provides).

For such a scenario, would I be correct that I need to do session cleanup for expired sessions myself? Probably a short cron task that calls DataManager::clean()?

**Comment by jschrab-lc** [comment]
Thanks for saving me the trouble of posting this here!

**Comment by sandrodz** [comment]
Yes I see the same. I use dockerised php container, you can reproduce it easily here: https://github.com/wearede/DevCeption/tree/master/configs/docker/services/webserver
