### ISSUE TITLE
Wordpress 5.5.1 - An active PHP session was detected [Critical Issue]

### ISSUE THREAD

**Issue by EmmanuelHmar** [ericmann/wp-session-manager#85]
**Describe the bug**

Wordpress version 5.5.1

Under Tools -> Site Health

```
 Critical Issue

 An active PHP session was detected
 A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.
```

**To Reproduce**
1. Go to 'admin dashboard'
2. Click on 'Tools -> Site Health'
3. See error

**Expected behavior**

**Screenshots**
https://i.imgur.com/fnfzoZO.png

**Additional context**
Disabling the plugin makes the issue go away.

**Comment by mauserrifle** [comment]
Any information on why this is closed and not fixed?
